### PR TITLE
Robust primitive parsing

### LINKED ISSUE #59: Create robust parses for premitive types
`play-json` fails to parse primitive json values which does not exactly match in type. ie: 
- json value `{ "Low": "14.3" }` will failed to be parsed as a `Double` because its a json string. However we can convert this string value to a scala Double.
- json value `{ "StringId": 123123 }` will fail to be parsed as a `String` because its a json number.  However we can convert this number value to a scala String.

We have seen instances where redox's json type doesnt exactly match our model type, but can be easily parsed. If we can define more tolerant json `Reads` for these types. we can avoid these issues.

### PR DESCRIPTION
**Pull request by pulasthibandara**
Resolves #59 

Adds robust reads for scalar types. so that we can recover from parsing errors like having a JsString("123") in a place we're expecting an Int.

This further adds support for converting values like "true", "t", "1" to Booleans from JsStrings.

### CODE REVIEW

File: src/test/scala/com/github/vitalsoftware/util/RobustPrimitivesTest.scala [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+
+  trait TestScope extends RobustPrimitives with Scope
+
+  "RobustPrimitives" should {
+    "read as string" in new TestScope {
+      Reads.of[String].reads(JsBoolean(true)) mustEqual (JsSuccess("true"))
+      Reads.of[String].reads(JsBoolean(false)) mustEqual (JsSuccess("false"))
+      Reads.of[String].reads(JsNumber(123)) mustEqual (JsSuccess("123"))
+      Reads.of[String].reads(JsNumber(123.456)) mustEqual (JsSuccess("123.456"))
+
```
Comment (apatzer) [inline src/test/scala/com/github/vitalsoftware/util/RobustPrimitivesTest.scala]: Can you add a failure case in there as well?
I've noticed that `BigDecimal(string)` isn't wrapped in a `Try`. Should it be? Should you produce a `JsError` when an expected number is instead of "1234" something like ">15%" or "I'm actually just a string"?

Comment (pulasthibandara) [reply src/test/scala/com/github/vitalsoftware/util/RobustPrimitivesTest.scala]: Oops, haven't completed this yet. Forgot to add the WIP. I'll be careful with the `BigDecimal`. Thanks

**Comment by pulasthibandara** [comment]
@apatzer The PR now complete.
